#!/usr/bin/env bash

SUPPORT_OS=(macos ubuntu)
HOMEBREW_URL=https://raw.githubusercontent.com/Homebrew/install/master/install

PACKAGE_NAME=Package\ Control
PACKAGE_URL=https://packagecontrol.io/Package%20Control.sublime-package
PACKAGE_FILE=Package\ Control.sublime-package
PACKAGE_DIR_MACOS=~/Library/Application\ Support/Sublime\ Text\ 3/Installed\ Packages
PACKAGE_DIR_UBUNTU=~/.config/sublime-text-3/Installed\ Packages

# detect os, return 0 if is_macos
function is_macos() {
  [[ "$(uname -s)" = "Darwin" ]] || return 1
}

# detect os, return 0 if is_ubuntu
function is_ubuntu() {
  [[ "$(cat /etc/issue 2> /dev/null)" =~ Ubuntu ]] || return 1
}

# loop through is_os functions
# if get_os 0 then get the match, or 1 to get the wrong match
function get_os() {
  for os in ${SUPPORT_OS[@]}; do
    is_${os}
    if [[ $? == ${1:-0} ]]; then
      echo ${os}
    fi
  done
}

function command_exists() {
  command -v "$@" > /dev/null 2>&1
}

function install_subl() {
  local os_name=$(get_os)
  if ! command_exists subl; then
    echo " => installing Sublime Text"
    case "${os_name}" in
      macos)
        if ! command_exists brew; then
          echo " => installing Homebrew..."
          /usr/bin/ruby -e "$(curl -fsSL ${HOMEBREW_URL})" > /dev/null 2>&1
            if [[ $? != 0 ]]; then
              echo " => unable to install Homebrew!"
              exit 1
            fi
          echo " => installing Homebrew...done"
        else
          echo "Ready to brew!"
        fi

        brew cask install sublime-text
        if [[ $? != 0 ]]; then
          echo " => unable to install Sublime Text!"
          exit 1
        fi
      ;;
      ubuntu)
        wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
        sudo apt-get install -y apt-transport-https
        echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
        sudo apt-get update -y
        sudo apt-get install -y sublime-text
      ;;
      *)
        echo "This script is limited to ${supported_os[@]}"
        exit 1
      ;;
    esac
  else
    echo "Sublime Text 3 already exists..."
  fi
}

function install_package_control() {
    local os_name=$(get_os)
    case "${os_name}" in
      macos)
        local package=${PACKAGE_DIR_MACOS}/${PACKAGE_FILE}
        if [[ ! -f "${package}" ]]; then
          echo " => installing ${PACKAGE_NAME}..."
          mkdir -p "${PACKAGE_DIR_MACOS}" && \
          curl -fsSL "${PACKAGE_URL}" -o "${package}"
          if [[ $? != 0 ]]; then
            echo " => unable to download ${PACKAGE_NAME}!"
            exit 1
          fi
          echo " => installing ${PACKAGE_NAME}...done"
        else
          echo "${PACKAGE_NAME} already exists..."
        fi    
      ;;
      ubuntu)
        local package=${PACKAGE_DIR_UBUNTU}/${PACKAGE_FILE}
        if [[ ! -f "${package}" ]]; then
          echo " => installing ${PACKAGE_NAME}..."
          mkdir -p "${PACKAGE_DIR_UBUNTU}"
          wget -q "${PACKAGE_URL}" -O "${package}"
          if [[ $? != 0 ]]; then
            echo " => unable to download ${PACKAGE_NAME}!"
            exit 1
          fi
          echo " => installing ${PACKAGE_NAME}...done"
        else
          echo "${PACKAGE_NAME} already exists..."
        fi  
      ;;
      *)
        echo "This script is limited to ${supported_os[@]}"
        exit 1
      ;;
    esac
}

install_subl && install_package_control && \
echo "Sublime Text 3 has been succesfully deployed!"
